choco install -y 7zip.install
choco install -y adobereader
choco install -y bitwarden
choco install -y foxitreader
choco install -y googlechrome
choco install -y openoffice
choco install -y pdfsam
choco install -y thunderbird
choco install -y windirstat
